### PR TITLE
translation

### PR DESCRIPTION
**Pull request by poljos06**

### CODE REVIEW

**Comment by supermario** [comment]
@poljos06 this looks unfinished, can you please confirm if you intend to submit more?

**Comment by poljos06** [comment]
Thank you for reaching out I am short of time. but can I still submit?
Actually I made 2 accounts on github and one is @poljosrosjos and I already
submitted
OT4-C1. Localize Documentation — Testnet Guides
there I finished my translation.  but in this account I got short on time
on submitting
OT4-C2. Localize Documentation — Smart Contract Guides.
Thank you.

**Comment by supermario** [comment]
@poljos06 we don't accept multiple submissions via multiple accounts, as per the [Rules of engagement](https://github.com/Concordium/Testnet4-Challenges#rules-of-engagement).

Can you please close any duplicate pull requests you have not finished / are not submitting?

Thanks.

**Comment by poljos06** [comment]
yes I will close this account "@poljos06"

**Pull request closed without merging**
